### ISSUE TITLE
about music api

### ISSUE THREAD

**Issue by Charles-ccc** [yy9306/JMusic#1]
您好，我最近也在学习黄轶老师的vue music app，其中碰到一个问题就是当时从QQ音乐直接调用的api，现在用不了了，返回回来的数据是一些没用的东西，请问您是如何处理的。

**Comment by yy9306** [comment]
和推荐页面那个处理一样的， 加了referer和host限制，参考一下推荐页面的列表数据获取就好了

**Comment by Charles-ccc** [comment]
Emm，我是在最开始获取歌单列表的时候，就卡住了，导致这个项目一直没有进行下去，有点左右为难。代码如下：
//webpack.dev.config.js
before(app){
        app.get('/api/getDiscList', function (req, res) {
            const url = 'https://c.y.qq.com/splcloud/fcgi-bin/fcg_get_diss_by_tag.fcg'
            axios.get(url, {
                headers: {
                    referer: 'https//c.y.qq.com/',
                    host: 'c.y.qq.com'
                },
                params: req.query
            }).then((response) => {
                res.json(response.data)
            }).catch((err) => {
                console.log(err)
            })
        })
    }

其实数据倒是取回来了，但是数据不对，感觉是链接的问题，你有空的话帮忙看看，谢谢。

**Comment by yy9306** [comment]
这个链接是对的， 我建议你去买正版的吧， 也不是很贵， 很值的， 黄轶老师一直在维护， 花点钱可能更快的学好， 不然你之后遇到的问题更多的
